import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', (e) => errors.push(String(e)));
await page.goto('http://localhost:5199/', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
await page.click('.track-card[data-track="space"]');
await page.waitForTimeout(3800);
await page.screenshot({ path: 'shots/sp1-run.png' });
await page.evaluate(() => window.__warp(2510));
await page.waitForTimeout(1500);
await page.screenshot({ path: 'shots/sp3-sun.png' });
await page.evaluate(() => window.__warp(2598));
await page.waitForTimeout(700);
await page.screenshot({ path: 'shots/sp4-blast.png' });
await page.waitForTimeout(900);
await page.screenshot({ path: 'shots/sp5-hole.png' });
await page.waitForTimeout(800);
await page.screenshot({ path: 'shots/sp6-suck.png' });
console.log(errors.length ? 'ОШИБКИ:\n' + errors.join('\n') : 'ок');
await browser.close();
